### ISSUE TITLE
feat: support collection scoped variables & headers

### ISSUE THREAD

**Issue by nohehf** [Escape-Technologies/graphman#4]
GraphMan should be able to take auth and headers as parameters. 
Those parameters as well as URLs should be sent in the environment variables.
The process could be to load .env files to generate different environment, or via the CLI.

**Comment by swangy** [comment]
yes! being able to include authentication headers would be fantastic, all our graphql endpoints are behind authentication checks

**Comment by nohehf** [comment]
What would you be interested in / what auth type do you use (tokens, API keys...) ?

**Comment by swangy** [comment]
Thanks for considering this feature!  We use JWT tokens for authentication so honestly, being able to pass key:value pairs in the header would work well for our workflow.

Using a .env for dev/staging/prod environments to populate the header value would be fantastic.

**Comment by swangy** [comment]
Also, being able to generate a key:value pair (Authorization:Bearer <token>) in each query header in the resulting postman collection

**Comment by nohehf** [comment]
Hey @swangy, while full env support isn't available right now, bearer token auth is now supported, see #16. You can use it with: `deno run [...] <URL> --auth=AUTHORIZATION_TOKEN` !

**Comment by swangy** [comment]
This is fantastic thanks very much!

you accepting PRs?  looking over deno to see what i can contribute

**Comment by nullswan** [comment]
@swangy 

We accept PR, feel free to contribute :)

**Comment by nohehf** [comment]
Closing this as [v1.2.1](https://github.com/Escape-Technologies/graphman/releases/tag/v1.2.1) enables all headers to be passed.
