### ISSUE TITLE
Documentation about run command is wrong

### ISSUE THREAD

**Issue by nullswan** [Escape-Technologies/graphman#40]
We must use `cli.ts` instead of `lib.ts` ?

`deno run https://deno.land/x/graphman@v1.1.2/src/cli.ts http://localhost:5013/graphql`

**Comment by nohehf** [comment]
Yes, you have to use `cli.ts` now. Where is the error please?

**Comment by nohehf** [comment]
Fixed: https://github.com/Escape-Technologies/graphman/commit/a4f8f7fa3df6ab3fcdd2315e5970c738ab80e673
