### ISSUE TITLE
Mutations not being separated into folder

### ISSUE THREAD

**Issue by bynho** [Escape-Technologies/graphman#41]
Hello, I saw that this issue was closed a few days ago (https://github.com/Escape-Technologies/graphman/issues/30) however when I run graphman, everything is still being placed under the queries folder.

I tried it with other APIs, such as this one: https://graphql-compose.herokuapp.com/northwind/

The end result is something similar to the below, as can be seen, it has mutations but it is stored under the queries array.

<img width="682" alt="Screenshot 2022-09-28 at 15 47 14" src="https://user-images.githubusercontent.com/32496933/192863994-9b3ce1c1-bde8-4b08-a4f2-4fb5540d2ac4.png">

As a separate question (not sure where to ask / apologies if it should be a separate issue).  Is there a way to organize the apis into named collections?  i.e. authentication, checkout etc?

**Comment by nohehf** [comment]
Hey thanks for opening the issue, I'll take a look at it ASAP! Tho for your second question I'm not sure I understand what's the matter, could you be more specific, please? Thanks

**Comment by nohehf** [comment]
Fixed in #43, I invite you to create a new issue for your second question, with more details if possible! Thanks for pointing this out @bynho
