### ISSUE TITLE
In Windows it generates an empty file 

### ISSUE THREAD

**Issue by SyedAsimAliSE** [Escape-Technologies/graphman#46]
Did a fresh install of Deno , ran the server locally - and getting only this empty file am I missing something here ?

![image](https://user-images.githubusercontent.com/44644354/200264755-f3e38a6f-26d4-4771-9c75-df67926b2f6e.png)

**Comment by nohehf** [comment]
Could you please retry using powershell rather than cmd?
Are you sure you don't have any file at `~/Desktop/out/*.postman_collection.json`?

**Comment by SyedAsimAliSE** [comment]
Yes Just tried with Power Shell and no luck, it just generates this empty localhost file.

![image](https://user-images.githubusercontent.com/44644354/202810620-c23f2fef-cd53-4db4-a41f-2d3bfa2ce541.png)

**Comment by nohehf** [comment]
Ok, I believe the issue might come from the parsing of the `:` in the file name. Could you try to expose your api on the default HTTPS port and retry (so you'd have an address without `:`)? Could you also run the example on the rick and morty API (see README), to confirm it's not a windows related issue? If confirmed it will be an easy parse fix. However, if not I cannot currently try it on a windows machine. Thanks :)

**Comment by SyedAsimAliSE** [comment]
Yes indeed it's the **:** parsing thing, with out port number and **:**  it is working perfect, and thanks man it saved me bunch of time writing long ass queries :D 

![image](https://user-images.githubusercontent.com/44644354/203396180-2eda4f43-1af0-48ac-a15d-702cf2109978.png)

**Comment by nohehf** [comment]
Glad it worked, will fix it today -> I'll add better parsing. My bad, this should have been working, but glad graphman helped you!
